name: Cypress Parallel Execution 3
on: 
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    # container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [6]
        ci_node_index: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Print current branch
        run: echo "The workflow has been triggered on ${GITHUB_REF#refs/heads/} branch."

      - name: Checkout code repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-modules
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.cache/Cypress
            **/node_modules

      - name: Install packages for Cypress
        id: cypress-package-install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Run Cypress E2E Tests
        id: cypress-run
        run: |
          npm run cy-test:parallel-node-${{matrix.ci_node_index}}

      - name: Save Cypress screenshot artifacts on failure
        uses: actions/upload-artifact@v1
        # if: steps.cypress-run.outputs.exit_code == 1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Save test results
        uses: actions/upload-artifact@v1
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: cypress/allure-results

  generate-report:
    runs-on: ubuntu-latest
    # container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: cypress-test

    steps:
      - name: Generate test reports
        id: generate reports
        run: |
          node cypress/cucumber-html-report.js

      - name: Save test report
        uses: actions/upload-artifact@v1
        if: always()
        continue-on-error: true
        with:
          name: html-report
          path: cypress/reports
